### ISSUE TITLE
assets directory not added and removed by Flowershow

### ISSUE THREAD

**Issue by ktneely** [flowershow/flowershow#661]
I'm trying to add an assets directory under content for hosting author images and other material.  The challenge is that I cannot get assets to "stick".

**Scenario 1: assets in Obsidian**

My first attempt was to create an `assets/` directory at the top level of the Obsidian vault as a peer of `blog/`, `people/`, etc.   Inside the folder was a single image, author.png` to be used in conjunction with a defined person. When updating flowershow with the "publish all notes" function in the plugin, my documents from all the other directories get uploaded, however, it skips the assets folder entirely.  

**Scenario 2: Adding via git**

Since the plugin was not adding the directory and file, I cloned the repo, added the directory and file under `content/`, and committed.  The Vercel build process kicked off and succeeds.  However, the image is not used within the blog posts as a part of the author.  Furthermore, when I update content and re-publish via Obsidian, it removes the folder and its underlying asset.  
Obsidian/Flowershow will remove `assets/` whether it is present in the vault or not.

To Reproduce

The following steps should reproduce the issue:
1. Create a new flowershow instance following the online guide
2. Use a new vault for this instance
3. publish the vault
4. add an `assets/` folder in Obsidian 
5. add an image file to the folder
6. publish
7. check repository under `content/` and the assets folder will not be there

Note: I can get the `assets/` folder to "stick" if I add a dummy Markdown file under it, however, the images are not pushed.

You can also immediately see that the asset file(s) will be deleted with the flowershow plugin widget.  There should be a way to add the assets to the plugin's tracking mechanism.

**Comment by rufuspollock** [comment]
@ktneely thanks for reporting. Are you using the Obsidian plugin?

**Comment by ktneely** [comment]
Yes, I am using the Obsidian plugin method.  I reviewed a related issue that mentioned symlinking the assets folder, but that doesn't seem to be relevant here, since I'm not referencing the assets as being under the `blog/` directory, and assets and blog are at the same level .

**Comment by rufuspollock** [comment]
@ktneely the `assets` folder has to be in or symlinked into the `public` folder usually.

**Comment by ktneely** [comment]
I don't have an explicit `public` directory, is that required?  My directory tree looks like this (I've cut some content directories out)

```
.
├── .obsidian/
├── assets/
│   ├── Headshot.png
│   └── assets.md
├── blog/
│   ├── 2024-03-27-Tier-1-Go-Bag.md
│   ├── 2025-01-16-Analysis-Toolkit-Part-2.md
├── people/
│   └── Kevin.md
├── projects/
└── index.md

```


Should there be a symlink like`blog/assets -> ../assets/` ?   I thought I tried that and it didn't work, but now can't quite remember.

**Comment by rufuspollock** [comment]
FIXED. Yes you want an explicit public directory and you have to symlink assets in there ... (annoying i know!)

**Comment by ktneely** [comment]
Still doesn't seem to work.  In the directory structured listed above, I created a symlink from the blog directory to the assets directory like so:

```shell
ktneely@falcon:~/dev/blog/content/blog$ ln -s ../assets/ ./assets
ktneely@falcon:~/dev/blog/content/blog$ ll
total 60
drwxr-xr-x  2 ktneely ktneely  4096 Feb 18 22:56  ./
drwxr-xr-x 10 ktneely ktneely  4096 Feb 18 22:56  ../
-rw-r--r--  1 ktneely ktneely  4422 Jan  7 09:59 'blog post 2024.md'
lrwxrwxrwx  1 ktneely ktneely    10 Feb 18 22:56  assets -> ../assets//
```

both of which are in the `content` directory.  Upon commit, which compiled cleanly according to Vercel, this still does not link to the profile picture.
